// models/index.js — central export for all VoyageCRM models
module.exports = {
  Tenant:               require('./Tenant'),
  User:                 require('./User'),
  AuditLog:             require('./AuditLog'),
  TagDefinition:        require('./TagDefinition'),
  Contact:              require('./Contact'),
  ContactTag:           require('./ContactTag'),
  ContactRelationship:  require('./ContactRelationship'),
  PipelineStage:        require('./PipelineStage'),
  Activity:             require('./Activity'),
  Notification:         require('./Notification'),
  EmailTemplate:        require('./EmailTemplate'),
  EmailSend:            require('./EmailSend'),
  Quote:                require('./Quote'),
  Booking:              require('./Booking'),
  BookingPassenger:     require('./BookingPassenger'),
  BookingSegment:       require('./BookingSegment'),
  ItineraryVersion:     require('./ItineraryVersion'),
  Supplier:             require('./Supplier'),
  SupplierContract:     require('./SupplierContract'),
  FinancialEvent:       require('./FinancialEvent'),
  PaymentSchedule:      require('./PaymentSchedule'),
  Commission:           require('./Commission'),
  Document:             require('./Document'),
};
