import { BRAND } from '../config/branding';

const baseStyles = `
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Poppins',sans-serif;background:#fff;color:#1A1A2E;font-size:14px;line-height:1.5;position:relative}
.doc-header{background:#ffffff;color:#1A1A2E;padding:28px 40px;display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid ${BRAND.navy}}
.doc-logo-img{height:45px;object-fit:contain}
.doc-header-meta{text-align:right;font-size:11px;color:#454C66;line-height:1.7}
.doc-body{padding:32px 40px}
.doc-row{display:flex;justify-content:space-between;gap:24px;margin-bottom:28px}
.doc-col{flex:1}
.doc-label{font-size:10px;font-weight:600;color:#8A90A6;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px}
.doc-value{font-size:13px;color:#1A1A2E;line-height:1.5}
.doc-title{font-size:20px;font-weight:700;color:${BRAND.navy};margin-bottom:4px}
.doc-number{font-size:13px;color:#8A90A6}
table{width:100%;border-collapse:collapse;margin-bottom:24px}
th{background:${BRAND.navy};color:#fff;padding:10px 14px;text-align:left;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.4px}
td{padding:10px 14px;border-bottom:1px solid #E5E7EB;font-size:13px}
tr:nth-child(even) td{background:#F5F7FA}
.amount-col{text-align:right}
.total-row td{background:${BRAND.navy};color:#fff;font-weight:700;font-size:14px}
.total-row td.amount-col{color:${BRAND.green};font-size:16px}
.doc-footer{margin-top:32px;padding-top:16px;border-top:1px solid #E5E7EB;display:flex;justify-content:space-between;font-size:11px;color:#8A90A6}
.status-badge{display:inline-block;padding:3px 10px;border-radius:999px;font-size:11px;font-weight:600}
.status-draft{background:#F3F4F6;color:#6B7280}
.status-sent{background:#EEF9FF;color:#0077B6}
.status-accepted{background:#ECFDF5;color:#059669}
.status-expired{background:#FEF2F2;color:#DC2626}
.status-paid{background:#ECFDF5;color:#059669}
.status-overdue{background:#FEF2F2;color:#DC2626}
.status-partial{background:#FFFBEB;color:#D97706}
.note-box{background:#F5F7FA;border-left:3px solid ${BRAND.green};padding:12px 16px;margin-bottom:24px;font-size:12px;color:#454C66;border-radius:0 4px 4px 0}
.balance-row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #E5E7EB}
.balance-total{display:flex;justify-content:space-between;padding:10px 12px;background:${BRAND.navy};color:#fff;border-radius:6px;margin-top:4px}
.watermark {
  position: absolute;
  top: 45%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 350px;
  height: 350px;
  background-image: url('/logo_letterhead.png');
  background-repeat: no-repeat;
  background-position: center;
  background-size: contain;
  opacity: 0.06;
  pointer-events: none;
  z-index: 0;
}
@media print {
  .watermark {
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
    opacity: 0.06 !important;
  }
}
`;

const htmlDoc = (title, body) => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${title}</title>
<style>${baseStyles}</style>
</head>
<body style="position: relative; min-height: 100vh;">
  <div class="watermark"></div>
  <div style="position: relative; z-index: 1;">
    ${body}
  </div>
</body>
</html>`;

const header = (docType, number, date) => `
<div class="doc-header">
  <div>
    <img src="/logo.png" alt="Logo" class="doc-logo-img" />
  </div>
  <div class="doc-header-meta">
    <div>${BRAND.address}</div>
    <div>${BRAND.phone} &middot; ${BRAND.email}</div>
    <div>GSTIN: ${BRAND.gstin}</div>
    <div style="margin-top:6px;font-size:12px;font-weight:700;color:${BRAND.navy};">${docType}${number ? ` &middot; ${number}` : ''}</div>
    ${date ? `<div>${date}</div>` : ''}
  </div>
</div>`;

const footer = () => `
<div class="doc-footer">
  <div>Generated by NexusCRM &middot; ${BRAND.website}</div>
  <div>Thank you for choosing ${BRAND.name}</div>
</div>`;

const fmt = (n) => {
  const v = Number(n) || 0;
  return `&#8377;${v.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const fmtDate = (d) =>
  d ? new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }) : '&mdash;';

const statusClass = (s = '') =>
  `status-badge status-${s.toLowerCase().replace(/\s+/g, '-')}`;

export const generateQuoteHTML = (quote = {}) => {
  const items = Array.isArray(quote.items) ? quote.items : [];
  const total = items.reduce((s, i) => s + (Number(i.amount) || 0), 0);

  const itemRows = items.length
    ? items.map(i => `
      <tr>
        <td>${i.description || '&mdash;'}</td>
        <td>${i.nights || '&mdash;'}</td>
        <td>${i.pax || '&mdash;'}</td>
        <td class="amount-col">${fmt(i.unit_price)}</td>
        <td class="amount-col">${fmt(i.amount)}</td>
      </tr>`).join('')
    : `<tr><td colspan="5" style="text-align:center;color:#8A90A6;padding:24px;">No line items on this quote.</td></tr>`;

  const body = `
${header('QUOTATION', quote.quote_number || (quote.id ? `#${quote.id}` : ''), fmtDate(quote.created_at))}
<div class="doc-body">
  <div class="doc-row">
    <div class="doc-col">
      <div class="doc-title">Quotation</div>
      <div class="doc-number">${quote.quote_number || (quote.id ? `#${quote.id}` : '')}</div>
      ${quote.status ? `<div style="margin-top:8px;"><span class="${statusClass(quote.status)}">${quote.status}</span></div>` : ''}
    </div>
    <div class="doc-col" style="text-align:right;">
      <div class="doc-label">Prepared For</div>
      <div class="doc-value" style="font-weight:600;">${quote.contact_name || quote.client || '&mdash;'}</div>
      ${(quote.contact_email || quote.email)
        ? `<div class="doc-value" style="font-size:12px;color:#8A90A6;">${quote.contact_email || quote.email}</div>`
        : ''}
      <div style="margin-top:10px;">
        <div class="doc-label">Valid Until</div>
        <div class="doc-value">${fmtDate(quote.expiry_date || quote.expires_at)}</div>
      </div>
    </div>
  </div>

  ${quote.booking_ref ? `
  <div style="margin-bottom:20px;">
    <div class="doc-label">Booking Reference</div>
    <div class="doc-value">${quote.booking_ref}</div>
  </div>` : ''}

  ${quote.destination ? `
  <div style="margin-bottom:20px;">
    <div class="doc-label">Destination / Package</div>
    <div class="doc-value" style="font-weight:600;font-size:15px;">${quote.destination}</div>
    ${quote.travel_dates ? `<div class="doc-value" style="color:#454C66;">${quote.travel_dates}</div>` : ''}
  </div>` : ''}

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th>Nights</th>
        <th>Pax</th>
        <th class="amount-col">Unit Price</th>
        <th class="amount-col">Amount</th>
      </tr>
    </thead>
    <tbody>
      ${itemRows}
      <tr class="total-row">
        <td colspan="4" style="text-align:right;padding-right:14px;">TOTAL</td>
        <td class="amount-col">${fmt(quote.total_amount || total)}</td>
      </tr>
    </tbody>
  </table>

  ${quote.notes ? `<div class="note-box">${quote.notes}</div>` : ''}

  <div style="font-size:11px;color:#8A90A6;margin-top:8px;">
    Prices are inclusive of applicable taxes unless otherwise stated.
    GST Invoice will be raised upon confirmation.
  </div>
  ${footer()}
</div>`;

  return htmlDoc(`Quote &mdash; ${quote.quote_number || quote.id || 'Draft'}`, body);
};

export const generateInvoiceHTML = (invoice = {}) => {
  const items = Array.isArray(invoice.items) ? invoice.items : [];
  const total = Number(invoice.total_amount) || items.reduce((s, i) => s + (Number(i.amount) || 0), 0);
  const paid  = Number(invoice.paid_amount) || 0;
  const outstanding = total - paid;

  const itemRows = items.length
    ? items.map(i => `
      <tr>
        <td>${i.description || '&mdash;'}</td>
        <td>${i.hsn || '&mdash;'}</td>
        <td class="amount-col">${fmt(i.taxable_amount ?? i.amount)}</td>
        <td class="amount-col">${fmt(i.gst_amount || 0)}</td>
        <td class="amount-col">${fmt(i.amount)}</td>
      </tr>`).join('')
    : `<tr><td colspan="5" style="text-align:center;color:#8A90A6;padding:24px;">No line items on this invoice.</td></tr>`;

  const body = `
${header('TAX INVOICE', invoice.invoice_number || (invoice.id ? `#${invoice.id}` : ''), fmtDate(invoice.invoice_date || invoice.created_at))}
<div class="doc-body">
  <div class="doc-row">
    <div class="doc-col">
      <div class="doc-title">Tax Invoice</div>
      <div class="doc-number">${invoice.invoice_number || (invoice.id ? `#${invoice.id}` : '')}</div>
      ${invoice.status ? `<div style="margin-top:8px;"><span class="${statusClass(invoice.status)}">${invoice.status}</span></div>` : ''}
    </div>
    <div class="doc-col" style="text-align:right;">
      <div class="doc-label">Bill To</div>
      <div class="doc-value" style="font-weight:600;">${invoice.contact_name || invoice.client || '&mdash;'}</div>
      ${invoice.contact_address ? `<div class="doc-value" style="font-size:12px;color:#8A90A6;">${invoice.contact_address}</div>` : ''}
      <div style="margin-top:10px;">
        <div class="doc-label">Due Date</div>
        <div class="doc-value">${fmtDate(invoice.due_date)}</div>
      </div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th>HSN / SAC</th>
        <th class="amount-col">Taxable Amt</th>
        <th class="amount-col">GST</th>
        <th class="amount-col">Total</th>
      </tr>
    </thead>
    <tbody>
      ${itemRows}
      <tr class="total-row">
        <td colspan="4" style="text-align:right;padding-right:14px;">INVOICE TOTAL</td>
        <td class="amount-col">${fmt(total)}</td>
      </tr>
    </tbody>
  </table>

  <div style="display:flex;justify-content:flex-end;margin-bottom:24px;">
    <div style="min-width:280px;">
      <div class="balance-row">
        <span style="color:#454C66;">Invoice Total</span>
        <span style="font-weight:600;">${fmt(total)}</span>
      </div>
      <div class="balance-row">
        <span style="color:#454C66;">Amount Paid</span>
        <span style="font-weight:600;color:${BRAND.green};">${fmt(paid)}</span>
      </div>
      <div class="balance-total">
        <span style="font-weight:600;">Balance Due</span>
        <span style="font-weight:700;font-size:16px;color:${outstanding > 0 ? '#E19D19' : BRAND.green};">${fmt(outstanding)}</span>
      </div>
    </div>
  </div>

  ${invoice.notes ? `<div class="note-box">${invoice.notes}</div>` : ''}

  <div style="font-size:11px;color:#8A90A6;margin-top:8px;">
    This is a computer-generated invoice. Please retain for your records. Payment via NEFT / UPI.
  </div>
  ${footer()}
</div>`;

  return htmlDoc(`Invoice &mdash; ${invoice.invoice_number || invoice.id || 'Draft'}`, body);
};

export const generateItineraryHTML = (booking = {}) => {
  const days = Array.isArray(booking.days) ? booking.days : [];

  const dayBlocks = days.length
    ? days.map((d, i) => `
      <div style="margin-bottom:20px;padding:16px;border:1px solid #E5E7EB;border-radius:8px;">
        <div style="font-weight:700;color:${BRAND.navy};margin-bottom:8px;">
          Day ${i + 1}${d.title ? ` &mdash; ${d.title}` : ''}
        </div>
        <div style="color:#454C66;font-size:13px;line-height:1.6;">${d.description || d.notes || 'Free time / transfer day'}</div>
        ${d.accommodation ? `<div style="margin-top:8px;font-size:12px;"><span style="color:#8A90A6;">Stay:</span> ${d.accommodation}</div>` : ''}
        ${d.meals ? `<div style="font-size:12px;"><span style="color:#8A90A6;">Meals:</span> ${d.meals}</div>` : ''}
      </div>`).join('')
    : '<div style="color:#8A90A6;text-align:center;padding:24px;">Itinerary details not yet added.</div>';

  const body = `
${header('ITINERARY', booking.booking_ref || booking.id, fmtDate(booking.created_at))}
<div class="doc-body">
  <div class="doc-row">
    <div class="doc-col">
      <div class="doc-title">${booking.destination || 'Custom Itinerary'}</div>
      <div class="doc-number">${booking.booking_ref || ''}</div>
    </div>
    <div class="doc-col" style="text-align:right;">
      <div class="doc-label">Guest</div>
      <div class="doc-value" style="font-weight:600;">${booking.contact_name || '&mdash;'}</div>
      <div style="margin-top:8px;">
        <div class="doc-label">Travel Period</div>
        <div class="doc-value">${fmtDate(booking.travel_dates?.start)} &ndash; ${fmtDate(booking.travel_dates?.end)}</div>
      </div>
    </div>
  </div>

  <div style="margin-bottom:24px;">${dayBlocks}</div>

  ${booking.inclusions ? `
  <div style="margin-bottom:16px;">
    <div style="font-weight:600;color:${BRAND.navy};margin-bottom:8px;">Inclusions</div>
    <div class="note-box">${booking.inclusions}</div>
  </div>` : ''}

  ${booking.exclusions ? `
  <div style="margin-bottom:16px;">
    <div style="font-weight:600;color:${BRAND.navy};margin-bottom:8px;">Exclusions</div>
    <div class="note-box" style="border-left-color:${BRAND.orange};">${booking.exclusions}</div>
  </div>` : ''}

  ${footer()}
</div>`;

  return htmlDoc(`Itinerary &mdash; ${booking.destination || booking.booking_ref || 'Trip'}`, body);
};

export const downloadDocument = (filename, htmlContent) => {
  const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
